dubbo:
  application:
    name: provider-service
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  scan:
    base-packages: com.zb.service.impl
  consumer:
    check: false #设置所有消费不检查
    timeout: 1000 #设置超市时间
    retries: 5 #设置重连次数